# Generated by Django 4.1.8 on 2023-09-06 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Talk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=300)),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")], default=1
                    ),
                ),
                (
                    "language",
                    models.CharField(choices=[("es", "Spanish"), ("en", "English")], default="es", max_length=2),
                ),
                ("timezone", models.CharField(max_length=60)),
                ("comments", models.CharField(max_length=300)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
