# Generated by Django 4.2.1 on 2023-10-07 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Talk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60, verbose_name="Name")),
                ("description", models.CharField(max_length=300, verbose_name="Description")),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")],
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("timezone", models.CharField(max_length=60, verbose_name="Timezone")),
                ("comments", models.CharField(max_length=300, verbose_name="Comments")),
                (
                    "precense",
                    models.PositiveIntegerField(
                        choices=[(1, "On site"), (2, "Virtual")], default=1, verbose_name="Precense"
                    ),
                ),
                ("months", models.CharField(blank=True, max_length=100, verbose_name="Months")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Talk",
            },
        ),
    ]
