# Generated by Django 4.1.8 on 2023-08-13 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkLanguage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="TalkLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Talk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=300)),
                ("timezone", models.CharField(max_length=60)),
                ("comments", models.CharField(max_length=300)),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="talks.talklanguage")),
                ("level", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="talks.talklevel")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
