# Generated by Django 4.1.8 on 2023-09-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talk",
            options={"verbose_name": "Talk"},
        ),
        migrations.AlterField(
            model_name="talk",
            name="comments",
            field=models.CharField(max_length=300, verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="talk",
            name="description",
            field=models.CharField(max_length=300, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="talk",
            name="language",
            field=models.CharField(
                choices=[("es", "Spanish"), ("en", "English")], default="es", max_length=2, verbose_name="Language"
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")], default=1, verbose_name="Level"
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="talk",
            name="timezone",
            field=models.CharField(max_length=60, verbose_name="Timezone"),
        ),
    ]
