# Generated by Django 4.2.1 on 2023-10-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talk",
            name="months",
            field=models.CharField(
                blank=True,
                help_text="Please write your time availability in months.The more specific, the better. E.g., October and November, any day after 6pm.",
                max_length=100,
                verbose_name="Months",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="timezone",
            field=models.CharField(
                help_text="Timezone of the place you are located. E.g., Colombia (UTC-5), Argentina or Chile (UTC-3), Mexico (UTC-6), etc.",
                max_length=60,
                verbose_name="Timezone",
            ),
        ),
    ]
