# Generated by Django 4.1.8 on 2023-08-12 16:41

from django.db import migrations, models
import temii.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=255, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to=temii.users.models.upload_to, verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Phone"),
        ),
    ]
