# Generated by Django 4.1.8 on 2023-08-12 05:01

from django.db import migrations, models
import temii.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_bio_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to=temii.users.models.upload_to, verbose_name="Image"
            ),
        ),
    ]
